application: boragle
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico  
  
- url: /static
  static_dir: static

- url: /stats.*
  script: appstats/ui.py
    
- url: .*
  script: main.py
